### ISSUE TITLE
URL-encode first line of request results in unexpected response

### ISSUE THREAD

**Issue by adayrodri** [elespike/burp-cph#14]
The first line of the request is url-encoded every time, even when the path/parameters were not modified. In many cases this results in an improper response from the server. I'd propose the following updates:
1) url-encode the first line of the request Only if it was modified
2) adding a checkbox for setting on/off the url-encoded feature

Excellent work, thank you.

**Comment by elespike** [comment]
@adayrodri, thanks for the feedback! I do believe I can implement the updates you've suggested, including the checkbox.

**Comment by elespike** [comment]
@adayrodri I've got this working in the latest commit to the current development branch, if you'd like to give that a shot:
https://github.com/elespike/burp-cph/commit/60dd226bb2ebf37a12c6e2fd4ed6207bf5be5f1f
