### ISSUE TITLE
Add option to duplicate tabs

### ISSUE THREAD

**Issue by elespike** [elespike/burp-cph#2]
Useful when configuring a new tab requires only minor changes to an already-configured tab.

This could either be a button on each tab (presumably at the top, with the move buttons) and/or some sort of control in the Options tab.

**Comment by elespike** [comment]
Should be working as intended and should have taken into account all use cases (including bad ones), extra testing is still a good idea.

**Comment by eth0up** [comment]
This has been complete, the Clone button works as expected.
