### ISSUE TITLE
Change the regex system to support back references

### ISSUE THREAD

**Issue by d0nutptr** [elespike/burp-cph#24]
Hello!

I propose we add support for [back references](https://regular-expressions.mobi/refcapture.html?wlr=1) in the find/replace system. As part of this, we should also closely examine the replacement code because some cases of regex are not supported correctly.

For example: `(?<=abc)(def)` on the text `"xyzdefabcdef"` with replacement of `"ghi"` results in `"xyzghiabcghi"` because the system, while it executes the search properly at first, ends up using simplistic search instead because it tries to find matches to values it matched on, which is incorrect behavior.

https://github.com/elespike/burp-cph/blob/master/CustomParamHandler.py#L393-L395

https://github.com/elespike/burp-cph/blob/master/CustomParamHandler.py#L498-L502

**Comment by elespike** [comment]
This was a deliberate design for some reason which now escapes me. I'll play around with this again and see how it could work.

**Comment by elespike** [comment]
@d0nutptr, good draft ready at https://github.com/elespike/burp-cph/tree/elespike-dev. Haven't done all the tests I'd like yet, but feel free to take it for a spin.
