### ISSUE TITLE
Suggestion/Get the matched value and usend 

### ISSUE THREAD

**Issue by yehgdotnet** [elespike/burp-cph#26]
Hello Team 

I have read your help doc but couldn't find a relevant info.

Is it possible to use your CPH to 

1. Grab the match 
2. Send the matched string to remote host 

?

Thanks for the great plugin.

**Comment by elespike** [comment]
Hi, @yehgdotnet 

Can you provide some additional details around what you're trying to do?

If I understand this correctly, you're not looking to modify anything, but just match a string from one host and send it to another host?

**Comment by yehgdotnet** [comment]
Hi @elespike 

My usecase scenerio for CPH is:

For example, an application displays hidden input field with encoded data: `<input type="hidden" name="data" value="hex{{bas64{{base64}}}}">`

1. Grep the match using name="data" value="(.*?)"
2. Send/GET/POST this matched string to http://localhost/decoder.php?data=

decoder.php will output to console which will allow me to read decoded value without manual decoding.

**Comment by elespike** [comment]
Got it, I think I know how to go about it. Let me try a few things and I'll get back to ya.

**Comment by elespike** [comment]
@yehgdotnet, got a solution for ya. It involves using one of Burp's session handling action: run a post-request macro.

1. Configure a macro that contains just your request to `decoder.php`, doesn't matter what the value of `?data=` is, we'll use CPH to inject it.

2. Configure a session handling rule to run a post-request macro, as such:

![2](https://user-images.githubusercontent.com/14970655/39632829-31d0601c-4f84-11e8-9541-a0873ed9e99d.png)

Make sure to set the rule scope just right (maybe you'll need to enable it for Proxy requests, for example).

3. Configure a caching tab for CPH, as such:

![3](https://user-images.githubusercontent.com/14970655/39632872-4f5e83e8-4f84-11e8-9f3d-0e0c24fbd464.png)

4. Configure a CPH tab to inject the correct value into `decode.php?data=`:

![4](https://user-images.githubusercontent.com/14970655/39632905-66f5ef8c-4f84-11e8-8167-a21e6495144c.png)


I'm assuming you're comfortable with Burp's macros and session handling rules and whatnot. If that's not the case, feel free to ask for clarification and I'll provide some extra guidance.

**Comment by yehgdotnet** [comment]
Wow that's FANTASTIC!!! Let me try.
