### ISSUE TITLE
support for multiple regexp groups

### ISSUE THREAD

**Issue by Hipapheralkus** [elespike/burp-cph#27]
Hi,
I have parameters with unique name + value for each session in the GET request, which look like `_portlet_instance_cJ1vzbzA0fql_id=49006de3-de69-4f79-a882-cbff86cfb9b5`

I tried to set "Find matches to this expression" to `_portlet_instance_([a-zA-Z0-9]{12})_id=([\w-]{36})` and set the same regexp for replacement. However, when I check extender output, I get `[INFO] Match index [0]: matched "cJ1vzbzA0fql", replaced with "cJ1vzbzA0fql"` and no further change for the second group (index [1]).

I tried capturing the whole regexp `(_portlet_instance_[a-zA-Z0-9]{12}_id=[\w-]{36})` which works.
Are you planning on supporting multiple regexp groups?

**Comment by elespike** [comment]
Hi, @Hipapheralkus!

In short, yes, I'm looking into implementing full regex support. See also #24.

**Comment by elespike** [comment]
@Hipapheralkus, a functional draft is available at https://github.com/elespike/burp-cph/tree/elespike-dev.

Please note, however, that the behavior has changed. There's no odd, custom handling of groups anymore; now you can use the full regex group capability.

For example:
Find matches to this expression: `(aaa)(bbb)(ccc)`
Replace with a static value (which now can be a regex): `\1BBB\g3`
Result: `aaaBBBccc`

Caveat: if you're using numbers in the replacement regex, you will need to be specific about groups; e.g.:
match: `(111)(222)(333)`
wrong replace: `\1000\3`, result: `@0333`
correct replace: `\g<1>000\g<3>`, result: `111000333`

Lastly, that dev branch has not undergone all testing yet, so you may see some weird stuff.
