### ISSUE TITLE
Find/extract regexp in header/body/both

### ISSUE THREAD

**Issue by Hipapheralkus** [elespike/burp-cph#28]
Hi,
I see an environment, where in each response, there is a `x-request-path:` header, which basically reflects the entire URL. For example: `x-request-path: /web/index.hml?param1=2&paramX=Y&csrf=123`.

Is it possible to add support to matching expressions and extracting values within header, body, or both? 

For special csrf parameters, when I would try to parse them from HTTP response by some regexp, I have a feeling it matches the header first which uses incorrect value, and only 2nd match = the one in the body would be fresh and valid.
Thanks

**Comment by elespike** [comment]
@Hipapheralkus, this can already be done using the following mechanism:
https://elespike.github.io/burp-cph/#quickstart/indices

This allows you to select which matches to modify.
