### ISSUE TITLE
Single request per session option

### ISSUE THREAD

**Issue by Hipapheralkus** [elespike/burp-cph#29]
If there are complex CSRF parameters (e.g. name of the parameter is also of a unique value), currently, native Burp session management doesn't support handling them. When I want to configure it manually, and use as part of Active scanner, there are many more requests in session tracer. Would it be possible to somehow bind this extender to session manager, so that a request would be used only once per valid session? At the moment, when I have 2 tabs of CPH, each of which is set to replace "a value returned by issuing a single request", there are many extra requests made, whereas 1 or 2 per the entire session would be all that is necessary.
Many thanks

**Comment by elespike** [comment]
Hi, @Hipapheralkus!

If I understand this correctly, the existing caching mechanism should allow you to do this:
1. Configure a CPH tab to watch for the the response that sets the CSRF token:

![1](https://user-images.githubusercontent.com/14970655/39631132-5fbe4fc0-4f7f-11e8-8b70-6be0b030c33d.png)

2. Configure a second tab to use the first tab's cached value:

![2](https://user-images.githubusercontent.com/14970655/39631147-68283ff4-4f7f-11e8-8895-f90add61ed49.png)
