### ISSUE TITLE
Undo/Redo for CPH JTextFields

### ISSUE THREAD

**Issue by eth0up** [elespike/burp-cph#3]
If it is possible, we should implement CTRL+Z and CTRL+Y for Undo/Redo. When I accidentally overwrite something I have previously entered, there is no easy way to get it back.

**Comment by eth0up** [comment]
Burp supports Undo in the Repeater tab's Request Editor (likely other areas too)

**Comment by elespike** [comment]
Preliminary research on this suggests it may be a pretty intensive endeavor. =/

**Comment by elespike** [comment]
Successfully deployed in dev branch!
