### ISSUE TITLE
When loading CPH tabs that have "previously cached response" selections, they sometimes load the wrong cached tab

### ISSUE THREAD

**Issue by eth0up** [elespike/burp-cph#30]
Sometimes when loading CPH config, the wrong "previous tab cached response" tab is selected.

**Comment by eth0up** [comment]
This issue also occurs during a scan. You can watch it select the wrong/different tab in real time, and it causes the results of the scan to be inaccurate. It doesn't matter the orientation of each tab, and the issue was observed with multiple tabs that were configured to use a value from a previously cached response.

**Comment by eth0up** [comment]
(needs testing) Changed previously cached response logic, removed explicit setting of the combobox: https://github.com/elespike/burp-cph/tree/Cache_prev_tab?files=1

**Comment by elespike** [comment]
@eth0up, unfortunately your changes stop the dynamic updates for cached responses, so the first value might work but future values won't be extracted.

But I did get ideas from your work, and have come up with a way to handle caching that doesn't spaz out:
Commit - https://github.com/elespike/burp-cph/commit/da3e6437795aa3bc3241e4a9119a8ba423ee9823
Check it out in my [dev branch](https://github.com/elespike/burp-cph/tree/elespike-dev).
