### ISSUE TITLE
Extension doesn't play well with Logger++

### ISSUE THREAD

**Issue by andresriancho** [elespike/burp-cph#32]
I always use the Logger++ extension to see what goes out from Burp.

Lately I had to install CPH to "fix" some requests that the Scanner was generating. After enabling CPH I noticed that Logger++ is not showing the requests generated by the scanner in the log anymore.

Is there a way for both extensions to play well together?

**Comment by elespike** [comment]
Hi, @andresriancho! (w3af! :D)

That's weird, I'll mess around with it and see what's going on.

**Comment by elespike** [comment]
@andresriancho, I've been unable to recreate this so far. I had both CPH and Logger++ going, in different order (in the Extender tab), and performing request modifications. Still saw logs popping up for Scanner.

Can you confirm that only these 2 extensions are loaded, and tell me any other details that might help? Perhaps try it after resetting Burp to default settings?

**Comment by andresriancho** [comment]
Sorry for the incorrect bug report, I tried again and it seems to be working.
