### ISSUE TITLE
Host header mixup

### ISSUE THREAD

**Issue by andresriancho** [elespike/burp-cph#33]
CPH seems to be ignoring the target host / port for requests and instead using the value in the `Host` header.

After using the extension for a while I found that sending this via the repeater:

```http
GET /contact/ HTTP/1.1
Host: andresriancho.com
User-Agent: curl/7.58.0
Accept: */*
Pragma: no-cache
Cache-Control: no-cache, no-transform
Connection: close

```

With target configured to `foo.com` port `443`, will actually send an HTTP request to `andresriancho.com`!

This issue also applies to the scanner module. Because of this CPH issue, burp scanner identified a false positive saying `Out-of-band resource load (HTTP)`:

```
GET / HTTP/1.1
Host: gg0r2rg9pyf225f3cyqtigiiu90bszk18rvhj6.burpcollaborator.net
Pragma: no-cache
Cache-Control: no-cache, no-transform
Connection: close

HTTP/1.1 200 OK
Server: Burp Collaborator https://burpcollaborator.net/
X-Collaborator-Version: 4
Content-Type: text/html
Content-Length: 61

<html><body>3es6a1ziwfv5qpn6nkfsu4zjukgkugifigz</body></html>
```

When the target of that request was `foo.com` port 443.

AFAIK this doesn't have anything to do with the rules I configure in CPH, those rules are very simple and do not modify the host header in any way.

**Comment by andresriancho** [comment]
Maybe the host should be extracted like https://github.com/elespike/burp-cph/blob/master/CustomParamHandler.py#L137 , instead of parsing the `Host` header from the request string?

**Comment by elespike** [comment]
Hi, @andresriancho!

Yup, I originally wanted the Host header to redirect the request to that host because I was using it that way for something at the time.

Lately, I also realized that's incorrect behavior, as sometimes you need to test the Host header without changing the target.

I'm not sure if the original use case should be preserved, but I can always make it an option (default off) to change targets when the Host header has been modified.

**Comment by elespike** [comment]
@andresriancho, prototype available at https://github.com/elespike/burp-cph/tree/elespike-dev.

**Comment by andresriancho** [comment]
Sorry for the delay in my response. Which commit has the bug-fix?

**Comment by elespike** [comment]
https://github.com/elespike/burp-cph/commit/67ffc4b11a96d1286e4df60ee3fa0380bb9e4b97
It's pretty big, I decided to make explicit controls for this.

Alternatively, you could just comment these out from the master branch:
https://github.com/elespike/burp-cph/blob/master/CustomParamHandler.py#L280,L281
