### ISSUE TITLE
Regarding help in Session Handling with Burp Intruder and Custom Parameter Handler for Oauth App

### ISSUE THREAD

**Issue by santokri** [elespike/burp-cph#36]
My Problem statement : This is what I need and configured so far

1. After my Intruder requests starts getting HTTP/1.1 Unauthorized I have configured a Rule 1 with Rule Actions : Check session is valid
2. Under Check session is valid I have

Added a Macro to validate session ---> In this have added the PUT request I use in the Intruder 

Under Inspect response to determine session validity ---> In this have checked Locations : HTTP headers and Response body : to Look for expression
401 Unauthorized

Now checked if seesion is invalid, perform action below ---> Here I select Run a macro

I have added a macro POST request with username and password to authenticate to the application

3. Now my problem is how to retrieve the access token send through the above POST response and use the token in the Authorization : Bearer "access-token should be placed here" in this format in the subsequent PUT request in the Intruder when 401 Unauthorized is seen during the attack. 

4. I have Customer Parameter Handler installed and would need steps on how to include and configure CPH when "After running the macro ,invoke a Burp extension action handler " is checked

**Comment by elespike** [comment]
@santokri,

Have you explored the following example?
https://github.com/elespike/burp-cph/wiki/07.-Extracting-replace-value-from-final-macro-response

It's analogous to what you're trying to achieve, if I understand your scenario correctly.

**Comment by elespike** [comment]
Hi, @santokri 

Were you able to achieve what you needed? Can I close this issue?
