### ISSUE TITLE
CPH escapes special characters

### ISSUE THREAD

**Issue by gk0us** [elespike/burp-cph#37]
### Steps to reproduce
Put the following string in the expression field which is going to be used to update each field:
`/ \@"`

The result after the replacement will be:
`\/\ \@\"`

**Comment by elespike** [comment]
Indeed it does, if you have the RegEx box unchecked:
https://github.com/elespike/burp-cph/blob/master/CPH_Config.py#L1372

Is this preventing you from achieving a desired outcome, and have you tried it with the RegEx enabled? What's your use case?

**Comment by gk0us** [comment]
Indeed, in case of adding a JWT in CPH, with the RegEx checkbox selected, special characters are not escaped. I will get back to you when I try a more complex scenario.

I will try a more complex scenario and get back with the results.

**Comment by elespike** [comment]
Hi, @gk0us 

Were you able to achieve your objective? Can I close this issue, or did you spot a bug?

**Comment by gk0us** [comment]
I did not find any issues, when using the RegEx option enabled. Issue closed.
