### ISSUE TITLE
Special characters are not escaped for named groups

### ISSUE THREAD

**Issue by th3-s3m** [elespike/burp-cph#38]
In the modify_message function, when dynamically generating the regex value, special characters are not escaped if they're part of a named group (?P<{}>{}). When executing "match_exp = re_compile(exp + groups_exp)", groups_exp may contain special that will either generate an error or unexpected behavior.

**Workaround:**
In my case I was extracting a string that sometimes contains a + (base64-ish) with the following regex `"token": "(?P<token>[^"]+)`.
I substituted lines 462, 463
```
    match_exp = re_compile(exp + groups_exp)
    self.logger.debug('match_exp adjusted to:\n{}'.format(match_exp.pattern))
```
with
```
    try:
        match_exp = re_compile(exp + groups_exp.replace('+','\+'))
    except re_error as e:
        self.logger.error(exc_invalid_regex.format(ph_target_exp, e))
        return msg_as_string
```

This workaround only fixed my case (+ char in extracted group), groups_exp should be properly escaped for all regex special characters before being recompiled.

_Edit: workaround was not so clear._

**Comment by elespike** [comment]
Great catch, thank you!

Fixed here: https://github.com/elespike/burp-cph/commit/8d46886abc9d55101c5e1cc05dba313bed77df41#diff-d59f892b7de1f2c8e5a2321095f452b4R451
