### ISSUE TITLE
Utilizing cached responses

### ISSUE THREAD

**Issue by illnino** [elespike/burp-cph#39]
> It is not a bug, but an inquiry.

**Can i accomplish below with CPH?**

## Scenario

There are three endpoints calls in order: 
1. `/getToken`
2. `/verify`
3. `/confirm`

To call `/verify`, it requires a valid token from response of `/getToken`. In return, the server would return a unique identifier - `uniqueId`.

```
POST /verify
Authorization: my_token

{myorder: 1}

HTTP 200

{"uniqueId": 123}
```

To call `/confirm`, it requires a valid token from response of `/getToken` and a uniqueId from response of `/verify`.

```
POST /confirm
Authorization: my_token

{"uniqueId": 123, "myorder": 1}

HTTP 200
```

Both token and uniqueId are short-live.

**Comment by elespike** [comment]
Hello, @illnino 

Yes, and there are a few options depending on what your trigger is for the `/confirm` request.

Have a look at:
https://github.com/elespike/burp-cph/wiki/08.-Utilizing-cached-responses
https://github.com/elespike/burp-cph/wiki/06.-Macros-vs-CPH
https://github.com/elespike/burp-cph/wiki/09.-CPH-as-an-alternative-to-macros

If you still need a hand, could you elaborate a little more on the scenario? For instance:
- is `/confirm` your primary target (i.e., are you hitting this endpoint directly, for testing); OR
- do you have other target endpoints which require `/confirm` to respond successfully first?

**Comment by illnino** [comment]
Hi @elespike 

Thanks for your reply.

`/confirm` is my primary target, which i would like to know if any vulnerabilities.

But to call `/confirm`, i need to call `/getToken` to obtain a valid token, and call `/verify` to obtain a unique id first.

In a nutshell, it cant be scanned.

I am wondering if i could take advantage of CPH to automate the process. Thanks.

### Request 1 - getToken
```
POST /getToken

{"username": nino, "password": password}

HTTP 200

<saml>[token_value_goes_here]</saml>
```

### Request 2 - verify

- `x-saml` was obtained in request 1.

```
POST /verify
x-saml: <saml>[token_value_goes_here]</saml>

{myorder: 1}

HTTP 200

{"uniqueId": 123}
```


### Request 3 - confirm (also my target)

- `x-saml` was obtained in request 1.
- `uniqueId` was obtained in request 2.

```
POST /confirm
x-saml: <saml>[token_value_goes_here]</saml>

{"uniqueId": 123, "myorder": 1}

HTTP 200

```

**Comment by elespike** [comment]
@illnino, if `/confirm` is your primary target, I'd suggest:

1. A tab to trigger `/getToken` every time CPH sees a request to `/verify`
    1. This tab will also update the `token` in the request to `/verify`
2. A tab to trigger `/verify` every time CPH sees a request to `/confirm`
    1. This tab will also update the `uniqueId` in the request to `/confirm`
3. A tab to cache the response from `/getToken`
4. A tab to update `token` in the initial `/confirm` request using the cached response from step 3

While this approach will cause a new token to be issued for every request to `/confirm`, the advantage is that everything is configured in CPH and it's simpler than using Burp's session handling rules and macros. I've made a sample configuration file for you (you'll need to adjust the request fields and regular expressions):

[sample_config.json](https://github.com/elespike/burp-cph/files/3552306/gh_39.json.txt)

On the other hand, the advantage of using Burp's session handling rules and macros along with CPH is more accurate logic: you can check whether a token is still valid, and only obtain a new token if the current one is invalid. Check the wiki links I posted in my previous comment for some examples of how to do this, especially https://github.com/elespike/burp-cph/wiki/06.-Macros-vs-CPH.

**Comment by illnino** [comment]
Hi @elespike 

Thanks for your example json.

May I ask if the order of the tabs matter? It doesnt seem to match what you described above. `Cache Token` is in the 2nd place in your example json.

From what i understand about the example.json, in the traffic log we should see:

1. Request 1
```
POST /confirm
x-saml: <saml>[dummy_token]</saml>

{"uniqueId": [dummy_id], "myorder": 1}

HTTP 403
```

2. Request 2
```
POST /verify
x-saml: <saml>[dummy_token]</saml>

{myorder: 1}

HTTP 403
```

3. Request 3
```
POST /getToken

{"username": nino, "password": password}

HTTP 200

<saml>[token_value]</saml>
```

4. Request 4
```
POST /verify
x-saml: <saml>[token_value_in_req_3]</saml>

{myorder: 1}

HTTP 200
{"uniqueId": [real_unique_id]}
```

5. Request 5
```
POST /confirm
x-saml: <saml>[token_value_in_req_3]</saml>

{"uniqueId": [dummy_id], "myorder": 1}

HTTP 403
Invalid unique_id
```

6. Request 6
```
POST /confirm
x-saml: <saml>[token_value_in_req_3]</saml>

{"uniqueId": [real_unique_id_in_4], "myorder": 1}

HTTP 200
```

## Logic
1. Send a request to `/confirm` in repeater or proxy
2. `Tab - 'update uniqueId for /confirm'` in CPH will capture the request and send a new request to `/verify`
3. `Tab - 'Update token for /verify'` in CPH will capture `#2 request` and send a new request to `/getToken`
4. `Tab - 'Cache token'` in CPH will capture `#3 request` and cache the response
5. While `#4` is cached,  CPH will update token in `/verify` in `Tab - 'update token for /verify'` and `/confirm` in `Tab - 'update token for /confirm'`
6. While `#5`'s response is returned, CPH will update `UniqueId` and resend `/confirm`

**Comment by illnino** [comment]
Unfortunately, I cant get it worked. CPH did not update the values. Did I miss anything? Thanks.

Here is a sample server:
```
const express = require('express')
const app = express()
const port = 3000
const bodyParser = require('body-parser');

app.use(bodyParser.json())

app.get('/', (req, res) => res.send('Hello World!'))

app.listen(port, () => console.log(`Example app listening on port ${port}!`))

app.post('/', function (req, res) {
  res.send('Got a POST request')
})

app.post('/getToken', function (req, res) {
  res.json({
    saml: "<saml>xxx</saml>"
  })
})

app.post('/verify', function (req, res) {

  obj = JSON.stringify(req.headers)

  saml_header = JSON.parse(obj)['saml']

  if (saml_header == 'xxx') {
  	res.json({
	    uniqueid: "123"
	  })

  } else {
  	res.status(403).send({ error: "Invalid token." });
  }

  
})

app.post('/confirm', function (req, res) {
  
  obj = JSON.stringify(req.headers)

  saml_header = JSON.parse(obj)['saml']

  if (saml_header == 'xxx') {
  	   req_body = JSON.stringify(req.body)
  	   uniqueid = JSON.parse(req_body)['uniqueid']
  	   if (uniqueid == "123") {
  	   	res.send('ok.')
  	   } else {
  	   	res.send('sorry.')
  	   }



  } else {
  	res.status(403).send({ error: "Invalid token." });
  }




})

```

## Reproduction Steps
1. I have changed my host file to map example.com to 127.0.0.1.
2. Add example.com to my scope in Burp
3. Change port number 80 to 3000 in your sample.json.

**Comment by elespike** [comment]
Hi, @illnino 

The order of the tabs matters in the sense that they will be executed from left to right. That said, since you can scope each tab to only work with particular requests/responses, sometimes ordering isn't very important. In your case, some tabs matter.

I will highlight below when a tab should be in a particular position. Furthermore, I have created [this new config file](https://github.com/elespike/burp-cph/files/3581960/gh_39-2.json.txt) that works with the sample server you posted above.

> Note that I switched the config to use `127.0.0.1:3000` instead of `example.com` so you don't have to change your `hosts` file.

So here's how it'll work (you had it almost right):
1. Send a request to `/confirm` in repeater or proxy.
    a. This request will not be released until step 8!
Here's the one I used:
```http
POST /confirm HTTP/1.1
Host: 127.0.0.1:3000
saml: ###
Connection: close
Content-Type: application/json
Content-Length: 18

{"uniqueid":"###"}
```

2. The tab `Update uniqueId for /confirm` in CPH will capture the request and send a new request to `/verify`.
    a. This tab must be placed before the `Update token for /confirm` tab.

3. The tab `Update token for /verify` in CPH will capture the `/verify` request issued in step 2 and send a new request to `/getToken`
    a. This tab can be placed anywhere!

4. The tab `Cache token` in CPH will capture the `/getToken` request issued in step 3 and cache the response.
    a. This tab must be placed before the `Update token for /confirm` tab.

5. After `/getToken` is cached, CPH will update the token in the `/verify` request issued in step 2 using the tab `Update token for /verify`.
    a. The token for `/confirm` does not get updated quite yet.
    b. Make sure to have `Extender` checked under _Tool scope settings_ in the Options tab in CPH. This is because CPH itself is issuing the request to `/getToken`.

6. Now that the token in `/verify` has been updated, the tab `Update uniqueId for /confirm` finally receives the modified response from `/verify` and updates the `uniqueId`.

7. The tab `Update token for /confirm` now receives the original request from step 1, which hasn't yet been released from Burp. Then it reads the cached response from the `Cache token` tab, and updates the token in the original `/confirm` request without issuing any additional requests.
    a. This tab must be placed after the `Cache token` tab and after the `Update uniqueId for /confirm` tab.

8. Now that all tabs are done processing, the original request to `/confirm` is released with the proper modifications.

![image](https://user-images.githubusercontent.com/14970655/64397581-ce9dd000-d02f-11e9-94fa-94bbc3d11d7d.png)

**Comment by elespike** [comment]
@illnino, any news? Were you successful this time around?

**Comment by illnino** [comment]
Sorry for the late reply, @elespike . The config works like a charm. Thanks.

However, I still have a few questions.

1. Each tab has a checkbox next to the tab's name. I noticed the one for caching request doesnt have it enabled. Does it mean in CPH for caching request tabs, the checkbox will be ignored?
2. In Logger++, I saw three requests were sent in a sequence order as expected. But I found in the logs of `/confirm`, it would always be

```
POST /confirm HTTP/1.1
Host: 127.0.0.1:3000
saml: xxx
Connection: close
Content-Type: application/json
Content-Length: 18

{"uniqueid":"123"}
```

Even though I edited my original request sample in repeater as below:
```
POST /confirm HTTP/1.1
Host: 127.0.0.1:3000
saml: ###
Connection: close
Content-Type: application/json
Content-Length: 34

{"uniqueid":"***", "myorder": "1"}
```

Imagine `"myorder"` is a parameter that is required to call `/confirm`.

Why is that? It doesnt seem to be 'hardcoded'.

**Comment by elespike** [comment]
1. The caching mechanism works regardless of the checkbox. Since the whole purpose of that tab is to cache, there's no reason to enable it.

2. I can't be 100% sure without some additional details, but it sounds like you may need to adjust the RegEx when modifying `/confirm` (some of them were essentially `".+"`, for example, which would replace everything up to the last quote, thus erasing `myorder`)
Additionally, check that Logger++ is loaded _after_ CPH, so that the requests will only make it to Logger++ after CPH has already modified them.

**Comment by illnino** [comment]
For example

The correct request to call `/confirm` is

```
POST /confirm HTTP/1.1
Host: 127.0.0.1:3000
saml: [real_saml_token]
Connection: close
Content-Type: application/json
Content-Length: 34

{"uniqueid": "[real_uniqueid]", "myorder": "1"}

```

instead of 

```
POST /confirm HTTP/1.1
Host: 127.0.0.1:3000
saml: [real_saml_token]
Connection: close
Content-Type: application/json
Content-Length: 34

{"uniqueid": "[real_uniqueid]"}

```

> For simplicity, the sample server does not force it as a mandatory parameter.

I have tried to submit a request like below in repeater

```
POST /confirm HTTP/1.1
Host: 127.0.0.1:3000
saml: ###
Connection: close
Content-Type: application/json
Content-Length: 34

{"uniqueid": "####", "myorder": "1"}

```

But I found indeed CPH modified the request as below

```
POST /confirm HTTP/1.1
Host: 127.0.0.1:3000
saml: [real_saml_token]
Connection: close
Content-Type: application/json
Content-Length: 34

{"uniqueid": "[real_uniqueid]"}

```

I hope above clarifies.

**Comment by illnino** [comment]
Sorry I made a mistake. I didnot realize there is a debug window. By viewing the logs in EMV, I noticed there was an extra space that was added, that caused the Regex did not match `uniqueid`

**Comment by elespike** [comment]
Excellent, glad you worked it out. =)
