### ISSUE TITLE
Transparent global parsing of responses

### ISSUE THREAD

**Issue by Hipapheralkus** [elespike/burp-cph#43]
Would it be possible to add a global transparent rule to hook into all responses for parsing? As far as I can tell, at this point, CPH needs to create some traffic for parsing. I hope it will be more clear on my API example:

Request 1:
```
POST /api/v1/CreateNew HTTP/1.1

{"comment":"Just a test", "name":"Johnny"}
```

Response 1 (a unique identifier is used, which I need to parse and remember):
```
HTTP/1.1 201 Created

{"Identifier":"123456789"}
```

Request 2 (note the change in URL, to use parsed value from the last response):
`GET /api/v1/GetByID/123456789
`
Response 2:
```
HTTP/1.1 200 OK

{"comment":"Just a test", "name":"Johnny", "status":"New", "id":"123456789"}
```

At this point in time, I'm not aware of any Burp native functionality or Extender, which would allow for Actively scanning 1st request, while changing URL of the 2nd request, so that the scanner would only see 2nd response.  I think with CPH I'm not able to do it, because I don't want to issue a request, sequence of requests, nor cached value from previous CPH tab. If there could be a new entry, like "value returned from all responses" it would be awesome:)

If I could create a regexp like "hey CPH, please hook into every single response; parse the latest version by regexp; and then use it to change the request I need to" it would be perfect:)

**Comment by elespike** [comment]
Hi, @Hipapheralkus 

You can absolutely do that with CPH. =)

See https://github.com/elespike/burp-cph/wiki/08.-Utilizing-cached-responses

In short, you would set up one tab scoped to the first request, without doing any modifications on it. Then, a second tab scoped to the second request can look into the cached response of the first tab in order to make necessary modifications.

**Comment by Hipapheralkus** [comment]
This is perfect and thanks to your help, I was able to create what I needed:) Awesome and powerful extender:)

**Comment by elespike** [comment]
My pleasure, glad to hear! :D
