### ISSUE TITLE
Feature Request: Scan a parameter inside a base64 encoded string

### ISSUE THREAD

**Issue by riramar** [elespike/burp-cph#45]
Not sure if it's possible but I'd like to have Burp Scanner injecting inside a JWT in a request authorization header.
Is it possible to do that with the actual features?

**Comment by elespike** [comment]
Hi, @riramar

Short answer: not without some hackery, and CPH is probably not the best tool for this job.

Long answer:
- You could do it with Burp Intruder if you supplied the modified JWTs ahead of time; that is, you'd have to know and prepare the payloads in advance.
- You could try one of the following extensions:
    - [JSON Web Token Attacker](https://portswigger.net/bappstore/82d6c60490b540369d6d5d01822bdf61)
    - [JSON Web Tokens](https://portswigger.net/bappstore/f923cbf91698420890354c1d8958fee6)
    - [Python Scripter](https://portswigger.net/bappstore/eb563ada801346e6bdb7a7d7c5c52583)
    - [Buby](https://portswigger.net/bappstore/bd453f3f4b364b9fba4e40e1eb6e8fb0)
- You could do it by telling Burp to send its requests to another proxy that's capable of scripting, such as [mitmproxy](https://github.com/mitmproxy/mitmproxy) or [ZAP](https://www.zaproxy.org/).
- You could do it by writing your own Burp Extension that tells Burp Scanner [how to target the Authorization header](https://github.com/PortSwigger/burp-extender-api/blob/master/src/main/java/burp/IScannerInsertionPoint.java#L151-L165), and [how to build payloads for it](https://github.com/PortSwigger/burp-extender-api/blob/master/src/main/java/burp/IScannerInsertionPoint.java#L132-L149).
- You could do it with CPH by setting it up to modify requests from Scanner, then telling Scanner to target the Authorization header. You would also need a way for CPH know how to modify the payload, so you'd have to set up an HTTP server that would receive the raw payload from Scanner, and return a full JWT containing that payload. The flow would be something like:
    1. Scanner sends request with raw payload; e.g., `Authorization: Bearer <script>alert(1)</script>`
    2. CPH reads/pauses the Scanner request, and issues another request to your custom HTTP server containing the raw payload; e.g., `GET http://localhost/jwt?payload=<script>alert(1)</script>`
    3. Your custom HTTP server inserts the payload into a proper JWT, and returns the JWT in the body of the response.
    4. CPH grabs the JWT and uses it to replace the original Scanner payload in the original request, then finally releases that request.

Hope that helps!

**Comment by riramar** [comment]
Thanks a lot for a so complete answer! I'll check and if I can do it I'll let you know.
