### ISSUE TITLE
Find and replace with + and = symbols

### ISSUE THREAD

**Issue by GabrielN-23** [elespike/burp-cph#48]
Hi, using regex find and replace, when the dynamic value contains a + and a = in the pattern "+(.\*)?=", the picker fails to operate. 
Test case: 
I set up a python simplehttpserver to return a string. If the string matches the pattern +(.\*)?= then the entire process fails. Instead of replacing the string, it appends it. EG:

Request header: (found with regex "Basic .*"
Basic replaceme

Obtain string from request:
+=

Replace 'replaceme' with "+=":
Basic replacemeBasic +=

Expected replacement:
Basic +=
![image](https://user-images.githubusercontent.com/61276734/93218545-3ff38100-f762-11ea-9131-c88bec73436e.png)

![image](https://user-images.githubusercontent.com/61276734/93218632-57326e80-f762-11ea-89cd-d86f129799b7.png)

This is most noticable when trying to CPH B64 data, which contains + and = in the above pattern. 

When the string is =+, it works fine.

Regards,
rgb-rgb

**Comment by elespike** [comment]
Hi, rgb-rgb

Thanks for your detailed report! I did have a brief look when you submitted it but I still need to dig deeper and currently am pretty tied up with life, so bear with me. =)

**Comment by elespike** [comment]
@rgb-rgb 

Apologies for the delay. I haven't been able to reproduce your issue, unfortunately.
I'm running the latest version of Burp Community as of today:
![Screenshot_20210130_225555](https://user-images.githubusercontent.com/14970655/106375047-50da1300-634e-11eb-9096-1f4dbc225bcd.png)
