### ISSUE TITLE
Replace-expression escapes some characters (underscore, colon, backslash)

### ISSUE THREAD

**Issue by MartinRJ** [elespike/burp-cph#50]
The "replace" expression escapes some characters, I haven't found a way to suppress this.
That means, it's simply not possible to use it to replace the target with a value that contains for example an underscore, a backslash, or a colon.
Because it will be escaped, and become \_, \\ or \:

Example:
![image](https://user-images.githubusercontent.com/3988789/105679358-9c279800-5eee-11eb-9cec-9d74cb91bfb7.png)

**Comment by elespike** [comment]
Hi, @MartinRJ 

Thanks for reaching out. Indeed that is the case, and as far as I remember it's intended:
https://github.com/elespike/burp-cph/issues/37

I'll have a closer look to see if something's up. For now, does enabling regex on step 3 help you?

**Comment by MartinRJ** [comment]
No, it's not possible to get rid of it.

**Comment by MartinRJ** [comment]
Thank you much, it worked with RegEx enabled.

**Comment by elespike** [comment]
Excellent, I'm also making a few changes to make that particular field more intuitive and match the behavior you and #37 expected.
